# URL con usuario:password y el parámetro de autenticación admin
spring.mongodb.uri=mongodb://root:rootpassword@localhost:27017/admin?authSource=admin

# Nombre de la base de datos
spring.mongodb.database=spotify_db

# Muestro los logs de las consultas por consola
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

